[package]
name = "controller"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.28.1", default-features = false, features = ["events"] }
evdev = "0.13.0"
glob = "0.3.2"
nix = "0.29.0"
ratatui = "0.29.0"
